### ISSUE TITLE
How to provision DN/GW?

### ISSUE THREAD

**Issue by lucker7777** [s5uishida/open5gs_5gc_ueransim_vpp_upf_dpdk_sample_config#1]
Hello,

first of all, thanks for this great guide. Everything (except for my issue) works as intended. FYI, I moved from VM into Kubernetes environment, it works and transformation was surprisingly easy.

My question: I do not quite understand how is DN/GW connected to UPG-VPP. I see it is connected via control network, n6 network, but also DN network (that should be a tunnel basically?). In your guide, there is very little written about DN/GW. I assumed, you do not have a specific DN/GW implementation, so I figured that maybe this should be plain VM, where you just set up IPs and that's it. Is that right?

If yes, then how should I route traffic inside UPG-VPP towards DN/GW? I tried to do that, but the only thing I can reach from UE are internal UPG-VPP interfaces.

What is a purpose of upf-nwi-internet interface, then? It does not have an IP assigned. So, is UPG-VPP automatically using it as a default route for internet traffic? If yes, then it does not work for me.

Thanks
Martin

**Comment by s5uishida** [comment]
Hi @lucker7777 

In UPG-VPP, the DN/GW of N6 is set as the default GW as follows.

**init.conf**
```
ip route add 0.0.0.0/0 table 0 via 192.168.16.152 n6
```
Alternatively, you can simply use the router as the DN/GW.
